# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
    exclude:
    - release/outdated

variables:
  solutionPath: HardWaxReborn/HardWaxReborn


jobs:
- job: build_linux
  # pool section defines what agent the job will run on
  pool:
    # get a microsoft-hosted agent running the latest ubuntu linux.
    vmImage: 'ubuntu-latest'
  
  steps:
  

  - script: dotnet build -c Release
    displayName: dotnet build
    workingDirectory: $(solutionPath)
  

  - script: dotnet publish -c Release -o ../publish
    displayName: dotnet publish
    workingDirectory: $(solutionPath)
  


